on:
  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        run: |
          echo 'github = ${{ toJSON(github) }}'
          echo 'job = ${{ toJSON(job) }}'
          echo 'steps = ${{ toJSON(steps) }}'
          echo 'runner = ${{ toJSON(runner) }}'
          echo 'strategy = ${{ toJSON(strategy) }}'
          echo 'matrix = ${{ toJSON(matrix) }}'
          echo 'inputs = ${{ toJSON(inputs) }}'